### ISSUE TITLE
ng build is broken

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#149]
I was able to run `ng serve` and see the following output:

```
ng serve --open
Your global Angular CLI version (7.3.5) is greater than your local
version (7.3.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2020-06-11T16:39:57.693Z
Hash: 4b249a9f001c6483dd5e
Time: 18453ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 284 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 463 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 653 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.63 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.94 MB [initial] [rendered]
```

However, when I run `ng build` I see the following:

```
ng build --prod --aot=true --baseHref=. --prod=true --extractCss=true --namedChunks=false --outputHashing=all --sourceMap=false
Your global Angular CLI version (7.3.5) is greater than your local
version (7.3.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Warning: Can't resolve all parameters for DateTime in C:/Users/sam/cdss-dev/StateMod-Web/git-repos/owf-app-info-mapper-ng/info-mapper/src/app/map-components/statemod-classes/DateTime.ts: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for DateTime in C:/Users/sam/cdss-dev/StateMod-Web/git-repos/owf-app-info-mapper-ng/info-mapper/src/app/map-components/statemod-classes/DateTime.ts: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for DateTime in C:/Users/sam/cdss-dev/StateMod-Web/git-repos/owf-app-info-mapper-ng/info-mapper/src/app/map-components/statemod-classes/DateTime.ts: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for DateTime in C:/Users/sam/cdss-dev/StateMod-Web/git-repos/owf-app-info-mapper-ng/info-mapper/src/app/map-components/statemod-classes/DateTime.ts: (?). This will become an error in Angular v6.x

Date: 2020-06-11T16:38:20.319Z
Hash: a684a77c2a98d8ccea95
Time: 15319ms
chunk {0} runtime.26209474bfa8dc87a77c.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} es2015-polyfills.c5dd28b362270c767b34.js (es2015-polyfills) 56.4 kB [initial] [rendered]
chunk {2} main.fa4681da67b0e16d34dc.js (main) 128 bytes [initial] [rendered]
chunk {3} polyfills.41559ea504b9f00b6dea.js (polyfills) 130 bytes [initial] [rendered]
chunk {4} styles.d186476216c341df4179.css (styles) 242 kB [initial] [rendered]
chunk {scripts} scripts.1e136f07cbd337ad328e.js (scripts) 380 kB [entry] [rendered]

ERROR in : Error: Internal error: unknown identifier []
    at Object.importExpr$$1 [as importExpr] (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:24166:27)
    at C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:18099:37
    at Array.map (<anonymous>)
    at InjectableCompiler.depsArray (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:18065:25)
    at InjectableCompiler.factoryFor (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:18129:36)
    at InjectableCompiler.injectableDef (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:18148:44)
    at InjectableCompiler.compile (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:18158:106)
    at C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:24011:90
    at Array.forEach (<anonymous>)
    at AotCompiler._emitPartialModule2 (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:24011:25)
    at C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:24004:48
    at Array.reduce (<anonymous>)
    at AotCompiler.emitAllPartialModules2 (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler\bundles\compiler.umd.js:24003:26)
    at AngularCompilerProgram._emitRender2 (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler-cli\src\transformers\program.js:300:31)
    at AngularCompilerProgram.emit (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@angular\compiler-cli\src\transformers\program.js:201:22)
    at AngularCompilerPlugin._emit (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:879:49)
    at AngularCompilerPlugin._update (C:\Users\sam\cdss-dev\StateMod-Web\git-repos\owf-app-info-mapper-ng\info-mapper\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:676:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[INFO] ...done running 'ng build...'
[INFO] Changing to:  /c/Users/sam/cdss-dev/StateMod-Web/git-repos/cdss-app-statemod-web/webroot/datasets/colorado/2015/workflow/05-upload-to-cloud
[ERROR]
[ERROR] dist/app to sync to S3 does not exist:  /c/Users/sam/cdss-dev/StateMod-Web/git-repos/owf-app-info-mapper-ng/info-mapper/dist/info-mapper
```

**Comment by Nightsphere** [comment]
The application was unnecessarily using an @Injectable( ) tag, which was messing up the build process.
It has been removed and the build should be working as desired from now on. Closing this issue.
